services:
  lol99: # Project name
    build:
      context: .
      dockerfile: Dockerfile
    image: lol99   # 명시적으로 이미지 이름 지정
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # 로컬 소스코드 디렉토리 마운트 (경로는 상황에 맞게 수정)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --
    depends_on:
      - mysql_db
    networks:
      - app_network
    env_file:
      - ./.env

  mysql_db:
    container_name: Mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    env_file:
      - ./.env

networks:
  app_network:

volumes:
  mysql_data:

