services:
  lol99:
    container_name: lol99
    build:
      context: .
      dockerfile: Dockerfile
    image: lol99
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn asgi:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mysql_db
    networks:
      - app_network
    env_file:
      - ./.env

  mysql_db:
    container_name: Mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    env_file:
      - ./.env

networks:
  app_network:

volumes:
  mysql_data:

